-- MySQL Script generated by MySQL Workbench
-- Fri Apr  4 16:19:10 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema festival
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `festival` ;

-- -----------------------------------------------------
-- Schema festival
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `festival` DEFAULT CHARACTER SET utf8 ;
USE `festival` ;

-- -----------------------------------------------------
-- Table `LOCATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LOCATION` ;

CREATE TABLE IF NOT EXISTS `LOCATION` (
  `location_id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NOT NULL,
  `latitude` DECIMAL(10,8) NOT NULL,
  `longitude` DECIMAL(11,8) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `continent` VARCHAR(45) NULL,
  PRIMARY KEY (`location_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `address_UNIQUE` ON `LOCATION` (`address` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `FESTIVAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FESTIVAL` ;

CREATE TABLE IF NOT EXISTS `FESTIVAL` (
  `festival_id` INT NOT NULL AUTO_INCREMENT,
  `year` INT NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `image` VARCHAR(255) NULL,
  `image_description` TEXT NULL,
  `location_id` INT NOT NULL,
  PRIMARY KEY (`festival_id`),
  CONSTRAINT `fk_festival_location`
    FOREIGN KEY (`location_id`)
    REFERENCES `LOCATION` (`location_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `FESTIVAL` (`name` ASC) VISIBLE;

CREATE INDEX `location_id_idx` ON `FESTIVAL` (`location_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `VENUE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VENUE` ;

CREATE TABLE IF NOT EXISTS `VENUE` (
  `venue_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `max_capacity` INT NOT NULL,
  `image` VARCHAR(45) NULL,
  `image_description` TEXT NULL,
  PRIMARY KEY (`venue_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `VENUE` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `EVENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EVENT` ;

CREATE TABLE IF NOT EXISTS `EVENT` (
  `event_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `date` DATETIME NOT NULL,
  `description` TEXT NULL,
  `festival_id` INT NOT NULL,
  `venue_id` INT NOT NULL,
  PRIMARY KEY (`event_id`),
  CONSTRAINT `fk_event_festival`
    FOREIGN KEY (`festival_id`)
    REFERENCES `FESTIVAL` (`festival_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_venue`
    FOREIGN KEY (`venue_id`)
    REFERENCES `VENUE` (`venue_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `festival_id_idx` ON `EVENT` (`festival_id` ASC) VISIBLE;

CREATE INDEX `venue_id_idx` ON `EVENT` (`venue_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `STAFF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STAFF` ;

CREATE TABLE IF NOT EXISTS `STAFF` (
  `staff_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `age` INT NULL,
  `role` VARCHAR(45) NOT NULL,
  `experience_level` VARCHAR(45) NULL,
  `staff_type` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`staff_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EQUIPMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EQUIPMENT` ;

CREATE TABLE IF NOT EXISTS `EQUIPMENT` (
  `equipment_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `image` VARCHAR(45) NULL,
  `image_description` TEXT NULL,
  PRIMARY KEY (`equipment_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PERFORMER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PERFORMER` ;

CREATE TABLE IF NOT EXISTS `PERFORMER` (
  `performer_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `stage_name` VARCHAR(45) NOT NULL,
  `website` VARCHAR(45) NULL,
  `instagram` VARCHAR(45) NULL,
  `image` VARCHAR(45) NULL,
  `image_description` TEXT NULL,
  PRIMARY KEY (`performer_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `stage_name_UNIQUE` ON `PERFORMER` (`stage_name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PERFORMANCE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PERFORMANCE` ;

CREATE TABLE IF NOT EXISTS `PERFORMANCE` (
  `performance_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  `performer_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  PRIMARY KEY (`performance_id`),
  CONSTRAINT `fk_performance_performer`
    FOREIGN KEY (`performer_id`)
    REFERENCES `PERFORMER` (`performer_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_performance_event`
    FOREIGN KEY (`event_id`)
    REFERENCES `EVENT` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `performer_id_idx` ON `PERFORMANCE` (`performer_id` ASC) VISIBLE;

CREATE INDEX `event_id_idx` ON `PERFORMANCE` (`event_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ARTIST`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ARTIST` ;

CREATE TABLE IF NOT EXISTS `ARTIST` (
  `artist_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `birthdate` DATETIME NULL,
  `performer_id` INT NOT NULL,
  PRIMARY KEY (`artist_id`),
  CONSTRAINT `fk_artist_performer`
    FOREIGN KEY (`performer_id`)
    REFERENCES `PERFORMER` (`performer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `performer_id_UNIQUE` ON `ARTIST` (`performer_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `BAND`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BAND` ;

CREATE TABLE IF NOT EXISTS `BAND` (
  `band_id` INT NOT NULL AUTO_INCREMENT,
  `formation_date` DATETIME NULL,
  `performer_id` INT NOT NULL,
  PRIMARY KEY (`band_id`),
  CONSTRAINT `fk_band_performer`
    FOREIGN KEY (`performer_id`)
    REFERENCES `PERFORMER` (`performer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `performer_id_UNIQUE` ON `BAND` (`performer_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `GENRE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GENRE` ;

CREATE TABLE IF NOT EXISTS `GENRE` (
  `genre_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `parent_genre_id` INT NULL,
  PRIMARY KEY (`genre_id`),
  CONSTRAINT `fk_genre_genre`
    FOREIGN KEY (`parent_genre_id`)
    REFERENCES `GENRE` (`genre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `GENRE` (`name` ASC) VISIBLE;

CREATE INDEX `parent_genre_id_idx` ON `GENRE` (`parent_genre_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `VISITOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VISITOR` ;

CREATE TABLE IF NOT EXISTS `VISITOR` (
  `visitor_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(20) NULL,
  `age` INT NULL,
  PRIMARY KEY (`visitor_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `email_UNIQUE` ON `VISITOR` (`email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `TICKET`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TICKET` ;

CREATE TABLE IF NOT EXISTS `TICKET` (
  `ticket_id` INT NOT NULL AUTO_INCREMENT,
  `EAN_code` VARCHAR(45) NOT NULL,
  `category` VARCHAR(20) NOT NULL,
  `purchased_date` DATETIME NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `payment_method` VARCHAR(20) NOT NULL,
  `is_activated` TINYINT NOT NULL,
  `visitor_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  PRIMARY KEY (`ticket_id`),
  CONSTRAINT `fk_ticket_visitor`
    FOREIGN KEY (`visitor_id`)
    REFERENCES `VISITOR` (`visitor_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_event`
    FOREIGN KEY (`event_id`)
    REFERENCES `EVENT` (`event_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `visitor_id_idx` ON `TICKET` (`visitor_id` ASC) VISIBLE;

CREATE INDEX `event_id_idx` ON `TICKET` (`event_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `EAN_code_UNIQUE` ON `TICKET` (`EAN_code` ASC) VISIBLE;

--CREATE UNIQUE INDEX `unique_visitor_event` USING BTREE ON `TICKET` (`visitor_id`, `event_id`) VISIBLE;


-- -----------------------------------------------------
-- Table `RATING`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RATING` ;

CREATE TABLE IF NOT EXISTS `RATING` (
  `rating_id` INT NOT NULL AUTO_INCREMENT,
  `artist_interpretation` INT NOT NULL,
  `sound_lighting` INT NOT NULL,
  `stage_presence` INT NOT NULL,
  `organization` INT NOT NULL,
  `overall_impression` INT NOT NULL,
  `rating_comment` TEXT NULL,
  `rating_date` DATETIME NOT NULL,
  `visitor_id` INT NOT NULL,
  `performance_id` INT NOT NULL,
  PRIMARY KEY (`rating_id`),
  CONSTRAINT `fk_rating_visitor`
    FOREIGN KEY (`visitor_id`)
    REFERENCES `VISITOR` (`visitor_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rating_performance`
    FOREIGN KEY (`performance_id`)
    REFERENCES `PERFORMANCE` (`performance_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `visitor_id_idx` ON `RATING` (`visitor_id` ASC) VISIBLE;

CREATE INDEX `performance_id_idx` ON `RATING` (`performance_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `unique_visitor_performance` USING BTREE ON `RATING` (`visitor_id`, `performance_id`) VISIBLE;


-- -----------------------------------------------------
-- Table `RESALE_BUYER_QUEUE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RESALE_BUYER_QUEUE` ;

CREATE TABLE IF NOT EXISTS `RESALE_BUYER_QUEUE` (
  `queue_id` INT NOT NULL AUTO_INCREMENT,
  `interest_date` DATETIME NOT NULL,
  `ticket_category` VARCHAR(50) NULL,
  `event_id` INT NULL,
  `ticket_id` INT NULL,
  `visitor_id` INT NOT NULL,
  PRIMARY KEY (`queue_id`),
  CONSTRAINT `fk_resale_buyer_queue_visitor`
    FOREIGN KEY (`visitor_id`)
    REFERENCES `VISITOR` (`visitor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resale_buyer_queue_event`
    FOREIGN KEY (`event_id`)
    REFERENCES `EVENT` (`event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resale_buyer_queue_ticket`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `TICKET` (`ticket_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;

CREATE INDEX `visitor_id_idx` ON `RESALE_BUYER_QUEUE` (`visitor_id` ASC) VISIBLE;
CREATE INDEX `event_id_idx` ON `RESALE_BUYER_QUEUE` (`event_id` ASC) VISIBLE;
CREATE INDEX `ticket_id_idx` ON `RESALE_BUYER_QUEUE` (`ticket_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `RESALE_SELLER_QUEUE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RESALE_SELLER_QUEUE` ;

CREATE TABLE IF NOT EXISTS `RESALE_SELLER_QUEUE` (
  `queue_id` INT NOT NULL AUTO_INCREMENT,
  `listing_date` DATETIME NOT NULL,
  `visitor_id` INT NOT NULL,
  `ticket_id` INT NOT NULL,
  PRIMARY KEY (`queue_id`),
  CONSTRAINT `fk_resale_seller_queue_visitor`
    FOREIGN KEY (`visitor_id`)
    REFERENCES `VISITOR` (`visitor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resale_seller_queue_ticket`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `TICKET` (`ticket_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `visitor_id_idx` ON `RESALE_SELLER_QUEUE` (`visitor_id` ASC) VISIBLE;

CREATE INDEX `ticket_id_idx` ON `RESALE_SELLER_QUEUE` (`ticket_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `ticket_id_UNIQUE` ON `RESALE_SELLER_QUEUE` (`ticket_id` ASC) VISIBLE;

ALTER TABLE RESALE_SELLER_QUEUE ADD COLUMN is_processed BOOLEAN DEFAULT FALSE;
ALTER TABLE RESALE_BUYER_QUEUE ADD COLUMN is_processed BOOLEAN DEFAULT FALSE;

-- -----------------------------------------------------
-- Table `EVENT_STAFF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EVENT_STAFF` ;

CREATE TABLE IF NOT EXISTS `EVENT_STAFF` (
  `event_id` INT NOT NULL,
  `staff_id` INT NOT NULL,
  PRIMARY KEY (`event_id`, `staff_id`),
  CONSTRAINT `fk_event_staff_event`
    FOREIGN KEY (`event_id`)
    REFERENCES `EVENT` (`event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_staff_staff`
    FOREIGN KEY (`staff_id`)
    REFERENCES `STAFF` (`staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `staff_id_idx` ON `EVENT_STAFF` (`staff_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `VENUE_EQUIPMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VENUE_EQUIPMENT` ;

CREATE TABLE IF NOT EXISTS `VENUE_EQUIPMENT` (
  `venue_id` INT NOT NULL,
  `equipment_id` INT NOT NULL,
  PRIMARY KEY (`venue_id`, `equipment_id`),
  CONSTRAINT `fk_venue_equipment_venue`
    FOREIGN KEY (`venue_id`)
    REFERENCES `VENUE` (`venue_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venue_equipment_equipment`
    FOREIGN KEY (`equipment_id`)
    REFERENCES `EQUIPMENT` (`equipment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `equipment_id_idx` ON `VENUE_EQUIPMENT` (`equipment_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PERFORMER_GENRE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PERFORMER_GENRE` ;

CREATE TABLE IF NOT EXISTS `PERFORMER_GENRE` (
  `performer_id` INT NOT NULL,
  `genre_id` INT NOT NULL,
  PRIMARY KEY (`performer_id`, `genre_id`),
  CONSTRAINT `fk_performer_genre_performer`
    FOREIGN KEY (`performer_id`)
    REFERENCES `PERFORMER` (`performer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_performer_genre_genre`
    FOREIGN KEY (`genre_id`)
    REFERENCES `GENRE` (`genre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `genre_id_idx` ON `PERFORMER_GENRE` (`genre_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ARTIST_BAND`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ARTIST_BAND` ;

CREATE TABLE IF NOT EXISTS `ARTIST_BAND` (
  `artist_id` INT NOT NULL,
  `band_id` INT NOT NULL,
  `join_date` DATETIME NOT NULL,
  `leave_date` DATETIME NULL,
  PRIMARY KEY (`artist_id`, `band_id`),
  CONSTRAINT `fk_artist_band_artist`
    FOREIGN KEY (`artist_id`)
    REFERENCES `ARTIST` (`artist_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artist_band_band`
    FOREIGN KEY (`band_id`)
    REFERENCES `BAND` (`band_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `band_id_idx` ON `ARTIST_BAND` (`band_id` ASC) VISIBLE;




-- Table `COMPLETED_RESALE_TRANSACTIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `COMPLETED_RESALE_TRANSACTIONS` ;

CREATE TABLE IF NOT EXISTS `COMPLETED_RESALE_TRANSACTIONS` (
  `transaction_id` INT NOT NULL AUTO_INCREMENT,
  `buyer_queue_id` INT NOT NULL,
  `seller_queue_id` INT NOT NULL,
  `ticket_id` INT NOT NULL,
  `transaction_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `buyer_id` INT NOT NULL,
  `seller_id` INT NOT NULL,
  PRIMARY KEY (`transaction_id`))
ENGINE = InnoDB;

CREATE INDEX `idx_transaction_date` ON `COMPLETED_RESALE_TRANSACTIONS` (`transaction_date` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
USE `festival`;

DELIMITER $$

USE `festival`$$
DROP TRIGGER IF EXISTS `trg_location_validate_coordinates_before_insert` $$
USE `festival`$$
CREATE DEFINER = CURRENT_USER TRIGGER `festival`.`trg_location_validate_coordinates_before_insert`
BEFORE INSERT ON `LOCATION`
FOR EACH ROW
BEGIN
    -- 1. Check latitude range
    IF NEW.latitude < -90 OR NEW.latitude > 90 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Latitude must be between -90 and 90';
    END IF;

    -- 2. Check longitude range
    IF NEW.longitude < -180 OR NEW.longitude > 180 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Longitude must be between -180 and 180';
    END IF;
END$$


USE `festival`$$
DROP TRIGGER IF EXISTS `trg_location_validate_coordinates_before_update` $$
USE `festival`$$
CREATE DEFINER = CURRENT_USER TRIGGER `festival`.`trg_location_validate_coordinates_before_update`
BEFORE UPDATE ON `LOCATION`
FOR EACH ROW
BEGIN
    -- 1. Check latitude range
    IF NEW.latitude < -90 OR NEW.latitude > 90 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Latitude must be between -90 and 90';
    END IF;

    -- 2. Check longitude range
    IF NEW.longitude < -180 OR NEW.longitude > 180 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Longitude must be between -180 and 180';
    END IF;
END$$


USE `festival`$$
DROP TRIGGER IF EXISTS `trg_festival_validate_dates_before_insert` $$
USE `festival`$$
CREATE DEFINER = CURRENT_USER TRIGGER `festival`.`trg_festival_validate_dates_before_insert`
BEFORE INSERT ON `FESTIVAL`
FOR EACH ROW
BEGIN
    -- 1. Ensure end_date is after start_date
    IF NEW.end_date <= NEW.start_date THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'End date must be after start date';
    END IF;

    -- 2. Ensure both start_date and end_date match the provided festival year
    IF YEAR(NEW.start_date) != NEW.year OR YEAR(NEW.end_date) != NEW.year THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Festival dates must be in the specified year';
    END IF;
END$$


USE `festival`$$
DROP TRIGGER IF EXISTS `trg_festival_prevent_delete` $$
USE `festival`$$
CREATE DEFINER = CURRENT_USER TRIGGER `festival`.`trg_festival_prevent_delete`
BEFORE DELETE ON `FESTIVAL`
FOR EACH ROW
BEGIN
    -- Prevent deletion of festival records
    SIGNAL SQLSTATE '45000'
    SET MESSAGE_TEXT = 'Festivals cannot be cancelled or deleted';
END$$


USE `festival`$$
DROP TRIGGER IF EXISTS `trg_venue_validate_capacity_before_insert` $$
USE `festival`$$
CREATE DEFINER = CURRENT_USER TRIGGER `festival`.`trg_venue_validate_capacity_before_insert`
BEFORE INSERT ON `VENUE`
FOR EACH ROW
BEGIN
    -- Ensure that max_capacity is a positive number
    IF NEW.max_capacity <= 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Maximum capacity must be greater than 0';
    END IF;
END;$$


USE `festival`$$
DROP TRIGGER IF EXISTS `trg_venue_validate_capacity_before_update` $$
USE `festival`$$
CREATE DEFINER = CURRENT_USER TRIGGER `festival`.`trg_venue_validate_capacity_before_update`
BEFORE UPDATE ON `VENUE`
FOR EACH ROW
BEGIN
    -- Ensure that max_capacity is a positive number
    IF NEW.max_capacity <= 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Maximum capacity must be greater than 0';
    END IF;
END;$$


USE `festival`$$
DROP TRIGGER IF EXISTS `trg_event_validate_before_insert` $$
USE `festival`$$
CREATE DEFINER = CURRENT_USER TRIGGER `festival`.`trg_event_validate_before_insert`
BEFORE INSERT ON `EVENT`
FOR EACH ROW
BEGIN
    DECLARE fest_start DATETIME;
    DECLARE fest_end DATETIME;
    DECLARE event_count INT;

    -- 1. Fetch the start and end dates of the festival for this event
    SELECT start_date, end_date 
      INTO fest_start, fest_end 
      FROM FESTIVAL 
     WHERE festival_id = NEW.festival_id;

    -- 2. Ensure the event date is within the festival duration
    IF NEW.date < fest_start OR NEW.date > fest_end THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Event must be within festival dates';
    END IF;

    -- 3. Check for overlapping event at the same venue on the same day
    SELECT COUNT(*) 
      INTO event_count
      FROM EVENT e
     WHERE e.venue_id = NEW.venue_id
       AND DATE(e.date) = DATE(NEW.date);

    IF event_count > 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Event overlap: another event is already scheduled at this venue on the same date';
    END IF;
END$$


USE `festival`$$
DROP TRIGGER IF EXISTS `trg_event_prevent_deletion` $$
USE `festival`$$
CREATE DEFINER = CURRENT_USER TRIGGER `festival`.`trg_event_prevent_deletion`
BEFORE DELETE ON `EVENT`
FOR EACH ROW
BEGIN
    -- Prevent any attempt to delete an event
    SIGNAL SQLSTATE '45000'
    SET MESSAGE_TEXT = 'Events cannot be cancelled or deleted';
END$$


USE `festival`$$
DROP TRIGGER IF EXISTS `trg_staff_validate_before_insert` $$
USE `festival`$$
CREATE DEFINER = CURRENT_USER TRIGGER `festival`.`trg_staff_validate_before_insert`
BEFORE INSERT ON `STAFF`
FOR EACH ROW
BEGIN
    -- 1. Ensure experience_level is within accepted values
    IF NEW.experience_level NOT IN ('trainee', 'beginner', 'intermediate', 'experienced', 'expert') THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Invalid experience level. Must be one of: trainee, beginner, intermediate, experienced, expert';
    END IF;

    -- 2. Ensure staff_type is within accepted values
    IF NEW.staff_type NOT IN ('security', 'auxiliary', 'technical') THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Invalid staff type. Must be one of: security, auxiliary, technical';
    END IF;
END;$$


USE `festival`$$
DROP TRIGGER IF EXISTS `trg_staff_validate_before_update` $$
USE `festival`$$
CREATE DEFINER = CURRENT_USER TRIGGER `festival`.`trg_staff_validate_before_update`
BEFORE UPDATE ON `STAFF`
FOR EACH ROW
BEGIN
    -- 1. Ensure experience_level is within the allowed values
    IF NEW.experience_level NOT IN ('trainee', 'beginner', 'intermediate', 'experienced', 'expert') THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Invalid experience level. Must be one of: trainee, beginner, intermediate, experienced, expert';
    END IF;

    -- 2. Ensure staff_type is within the allowed values
    IF NEW.staff_type NOT IN ('security', 'auxiliary', 'technical') THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Invalid staff type. Must be one of: security, auxiliary, technical';
    END IF;
END;$$


USE `festival`$$
DROP TRIGGER IF EXISTS `trg_performance_validate_schedule_before_insert` $$
USE `festival`$$
CREATE DEFINER = CURRENT_USER TRIGGER `festival`.`trg_performance_validate_schedule_before_insert`
BEFORE INSERT ON `PERFORMANCE`
FOR EACH ROW
BEGIN
    DECLARE event_date DATETIME;
    DECLARE performer_conflict INT;

    -- 1. Get the date of the related event
    SELECT `date` INTO event_date
    FROM EVENT
    WHERE event_id = NEW.event_id;

    -- 2. Ensure end_time is after start_time
    IF NEW.end_time <= NEW.start_time THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'End time must be after start time';
    END IF;

    -- 3. Ensure performance takes place on the same day as the event
    IF DATE(NEW.start_time) != DATE(event_date) THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Performance must be on the same day as the event';
    END IF;

    -- 4. Check for overlapping performances by the same performer
    SELECT COUNT(*) INTO performer_conflict
    FROM PERFORMANCE p
    WHERE p.performer_id = NEW.performer_id
      AND ((NEW.start_time BETWEEN p.start_time AND p.end_time)
        OR (NEW.end_time BETWEEN p.start_time AND p.end_time)
        OR (p.start_time BETWEEN NEW.start_time AND NEW.end_time));

    IF performer_conflict > 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Performer is already scheduled for another performance at this time';
    END IF;

    -- 5. Ensure the duration does not exceed 3 hours
    IF TIMESTAMPDIFF(MINUTE, NEW.start_time, NEW.end_time) > 180 THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'Performance duration cannot exceed 3 hours';
	END IF;
    
END;$$


USE `festival`$$
DROP TRIGGER IF EXISTS `trg_performance_enforce_intervals_before_insert` $$
USE `festival`$$
CREATE DEFINER = CURRENT_USER TRIGGER `festival`.`trg_performance_enforce_intervals_before_insert`
BEFORE INSERT ON `PERFORMANCE`
FOR EACH ROW
BEGIN
    DECLARE prev_end_time DATETIME;
    DECLARE next_start_time DATETIME;
    DECLARE interval_before INT;
    DECLARE interval_after INT;

    -- 1. Find end time of the last performance before the current one in the same event
    SELECT MAX(end_time) INTO prev_end_time
    FROM PERFORMANCE
    WHERE event_id = NEW.event_id
      AND end_time < NEW.start_time;

    -- 2. Find start time of the next performance after the current one in the same event
    SELECT MIN(start_time) INTO next_start_time
    FROM PERFORMANCE
    WHERE event_id = NEW.event_id
      AND start_time > NEW.end_time;

    -- 3. Validate interval with the previous performance
    IF prev_end_time IS NOT NULL THEN
        SET interval_before = TIMESTAMPDIFF(MINUTE, prev_end_time, NEW.start_time);

        IF interval_before < 5 THEN
            SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Interval between performances must be at least 5 minutes';
        END IF;

        IF interval_before > 30 THEN
            SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Interval between performances cannot exceed 30 minutes';
        END IF;
    END IF;

    -- 4. Validate interval with the next performance
    IF next_start_time IS NOT NULL THEN
        SET interval_after = TIMESTAMPDIFF(MINUTE, NEW.end_time, next_start_time);

        IF interval_after < 5 THEN
            SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Interval between performances must be at least 5 minutes';
        END IF;

        IF interval_after > 30 THEN
            SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Interval between performances cannot exceed 30 minutes';
        END IF;
    END IF;
END;$$


USE `festival`$$
DROP TRIGGER IF EXISTS `trg_performance_limit_consecutive_years_before_insert` $$
USE `festival`$$
CREATE DEFINER = CURRENT_USER TRIGGER `festival`.`trg_performance_limit_consecutive_years_before_insert`
BEFORE INSERT ON `PERFORMANCE`
FOR EACH ROW
BEGIN
    DECLARE performer_id_to_check INT;
    DECLARE consecutive_years INT;
    DECLARE festival_year INT;

    -- 1. Store performer_id from the new row
    SET performer_id_to_check = NEW.performer_id;

    -- 2. Get the year of the festival for the new performance
    SELECT f.year INTO festival_year
    FROM EVENT e
    JOIN FESTIVAL f ON e.festival_id = f.festival_id
    WHERE e.event_id = NEW.event_id;

    -- 3. Check if performer participated in the previous 3 consecutive years
    SELECT COUNT(DISTINCT f.year) INTO consecutive_years
    FROM PERFORMANCE p
    JOIN EVENT e ON p.event_id = e.event_id
    JOIN FESTIVAL f ON e.festival_id = f.festival_id
    WHERE p.performer_id = performer_id_to_check
      AND f.year BETWEEN (festival_year - 3) AND (festival_year - 1)
    GROUP BY p.performer_id
    HAVING COUNT(DISTINCT f.year) = 3
       AND MIN(f.year) = festival_year - 3
       AND MAX(f.year) = festival_year - 1;

    -- 4. If true, prevent the insert
    IF consecutive_years = 3 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Performer cannot participate for more than 3 consecutive years';
    END IF;
END;$$


USE `festival`$$
DROP TRIGGER IF EXISTS `trg_visitor_validate_age_before_insert` $$
USE `festival`$$
CREATE DEFINER = CURRENT_USER TRIGGER `festival`.`trg_visitor_validate_age_before_insert`
BEFORE INSERT ON `VISITOR`
FOR EACH ROW
BEGIN
    -- Ensure age is between 1 and 99
    IF NEW.age <= 0 OR NEW.age >= 100 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Age must be between 0 and 100';
    END IF;
END;$$


USE `festival`$$
DROP TRIGGER IF EXISTS `trg_visitor_validate_age_before_update` $$
USE `festival`$$
CREATE DEFINER = CURRENT_USER TRIGGER `festival`.`trg_visitor_validate_age_before_update`
BEFORE UPDATE ON `VISITOR`
FOR EACH ROW
BEGIN
    -- Ensure age is between 1 and 99
    IF NEW.age <= 0 OR NEW.age >= 100 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Age must be between 0 and 100';
    END IF;
END;$$


USE `festival`$$
DROP TRIGGER IF EXISTS `trg_ticket_validate_before_insert` $$
USE `festival`$$
CREATE DEFINER = CURRENT_USER TRIGGER `festival`.`trg_ticket_validate_before_insert`
BEFORE INSERT ON `TICKET`
FOR EACH ROW
BEGIN
    DECLARE event_date DATETIME;
    DECLARE venue_capacity INT;
    DECLARE tickets_sold INT;
    DECLARE visitor_tickets INT;
    DECLARE vip_tickets INT;

    -- 1. Get event date and venue capacity
    SELECT e.date, v.max_capacity
    INTO event_date, venue_capacity
    FROM EVENT e
    JOIN VENUE v ON e.venue_id = v.venue_id
    WHERE e.event_id = NEW.event_id;

    -- 2. Ensure ticket is purchased before the event date
    IF NEW.purchased_date > event_date THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Ticket cannot be purchased after the event date';
    END IF;

    -- 3. Check if event is sold out
    SELECT COUNT(*) INTO tickets_sold
    FROM TICKET
    WHERE event_id = NEW.event_id;

    IF tickets_sold >= venue_capacity THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Event is sold out, no more tickets available';
    END IF;

    -- 4. Ensure visitor hasn't already purchased a ticket for this event
    SELECT COUNT(*) INTO visitor_tickets
    FROM TICKET
    WHERE visitor_id = NEW.visitor_id AND event_id = NEW.event_id;

    IF visitor_tickets > 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Visitor already has a ticket for this event';
    END IF;

    -- 5. VIP ticket limit (10% of venue capacity)
    IF NEW.category = 'vip' THEN
        SELECT COUNT(*) INTO vip_tickets
        FROM TICKET
        WHERE event_id = NEW.event_id AND category = 'vip';

        IF vip_tickets >= (venue_capacity * 0.1) THEN
            SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'VIP tickets are limited to 10% of venue capacity';
        END IF;
    END IF;

    -- 6. Ensure price is a positive value
    IF NEW.price <= 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Price must be greater than 0';
    END IF;

END;$$


USE `festival`$$
DROP TRIGGER IF EXISTS `trg_ticket_validate_before_update` $$
USE `festival`$$
CREATE DEFINER = CURRENT_USER TRIGGER `festival`.`trg_ticket_validate_before_update`
BEFORE UPDATE ON `TICKET`
FOR EACH ROW
BEGIN
    -- 1. Ensure price is greater than 0
    IF NEW.price <= 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Price must be greater than 0';
    END IF;

    -- 2. Ensure is_activated is 0 or 1
    IF NEW.is_activated NOT IN (0, 1) THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'is_activated must be either 0 or 1';
    END IF;

    -- 3. Validate ticket category
    IF NEW.category NOT IN ('General Admission', 'VIP', 'Early Bird', 'Premium') THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Category must be one of: General Admission, VIP, Early Bird, Premium';
    END IF;

    -- 4. Validate payment method
    IF NEW.payment_method NOT IN ('Credit Card', 'Debit Card', 'Bank Transfer') THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Payment method must be one of: Credit Card, Debit Card, Bank Transfer';
    END IF;

    -- 5. Allow activation (from 0 to 1)
    IF OLD.is_activated = 0 AND NEW.is_activated = 1 THEN
        SET NEW.is_activated = 1;

    -- 6. Prevent deactivation (from 1 to 0)
    ELSEIF OLD.is_activated = 1 AND NEW.is_activated = 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Activated tickets cannot be deactivated';
    END IF;
END;$$




USE `festival`$$
DROP TRIGGER IF EXISTS `trg_rating_validate_before_insert` $$
USE `festival`$$
CREATE DEFINER = CURRENT_USER TRIGGER `festival`.`trg_rating_validate_before_insert`
BEFORE INSERT ON `RATING`
FOR EACH ROW
BEGIN
    DECLARE perf_date DATETIME;
    DECLARE has_ticket BOOLEAN;
    DECLARE existing_rating INT;
    DECLARE event_id_for_perf INT;
    DECLARE error_message VARCHAR(255);

    -- Get the event_id for this performance
    SELECT p.event_id INTO event_id_for_perf
    FROM PERFORMANCE p
    WHERE p.performance_id = NEW.performance_id;

    -- 1. Get the end time of the performance
    SELECT p.end_time INTO perf_date
    FROM PERFORMANCE p
    WHERE p.performance_id = NEW.performance_id;

    -- 2. Ensure the rating is submitted after the performance ends
    IF NEW.rating_date < perf_date THEN
        SET error_message = CONCAT('Rating cannot be submitted before the performance ends. Visitor ID: ', 
                                  NEW.visitor_id, ', Performance ID: ', NEW.performance_id, 
                                  ', Rating date: ', NEW.rating_date, ', Performance end: ', perf_date);
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = error_message;
    END IF;

    -- 3. Ensure the visitor has a ticket for the event of the performance
    SELECT COUNT(*) > 0 INTO has_ticket
    FROM TICKET t
    JOIN EVENT e ON t.event_id = e.event_id
    JOIN PERFORMANCE p ON e.event_id = p.event_id
    WHERE t.visitor_id = NEW.visitor_id
      AND p.performance_id = NEW.performance_id;

    IF NOT has_ticket THEN
        SET error_message = CONCAT('Visitor must have a ticket to rate a performance. Visitor ID: ', 
                                  NEW.visitor_id, ', Performance ID: ', NEW.performance_id, 
                                  ', Event ID: ', event_id_for_perf);
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = error_message;
    END IF;

    -- 4. Ensure each rating score is between 1 and 5
    IF NEW.artist_interpretation < 1 OR NEW.artist_interpretation > 5 OR
       NEW.sound_lighting < 1 OR NEW.sound_lighting > 5 OR
       NEW.stage_presence < 1 OR NEW.stage_presence > 5 OR
       NEW.organization < 1 OR NEW.organization > 5 OR
       NEW.overall_impression < 1 OR NEW.overall_impression > 5 THEN
        SET error_message = CONCAT('Ratings must be between 1 and 5. Visitor ID: ', 
                                  NEW.visitor_id, ', Performance ID: ', NEW.performance_id);
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = error_message;
    END IF;

    -- 5. Prevent duplicate rating for the same performance by the same visitor
    SELECT COUNT(*) INTO existing_rating
    FROM RATING
    WHERE visitor_id = NEW.visitor_id
      AND performance_id = NEW.performance_id;

    IF existing_rating > 0 THEN
        SET error_message = CONCAT('Visitor has already rated this performance. Visitor ID: ', 
                                  NEW.visitor_id, ', Performance ID: ', NEW.performance_id);
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = error_message;
    END IF;
END;$$


USE `festival`$$
DROP TRIGGER IF EXISTS `trg_rating_validate_values_before_update` $$
USE `festival`$$
CREATE DEFINER = CURRENT_USER TRIGGER `festival`.`trg_rating_validate_values_before_update`
BEFORE UPDATE ON `RATING`
FOR EACH ROW
BEGIN
    DECLARE perf_date DATETIME;
    DECLARE has_ticket BOOLEAN;
    DECLARE existing_rating INT;
    DECLARE event_id_for_perf INT;
    DECLARE error_message VARCHAR(255);

    -- Get the event_id for this performance
    SELECT p.event_id INTO event_id_for_perf
    FROM PERFORMANCE p
    WHERE p.performance_id = NEW.performance_id;

    -- 1. Get the end time of the performance
    SELECT p.end_time INTO perf_date
    FROM PERFORMANCE p
    WHERE p.performance_id = NEW.performance_id;

    -- 2. Ensure the rating is submitted after the performance ends
    IF NEW.rating_date < perf_date THEN
        SET error_message = CONCAT('Rating cannot be submitted before the performance ends. Visitor ID: ', 
                                  NEW.visitor_id, ', Performance ID: ', NEW.performance_id, 
                                  ', Rating date: ', NEW.rating_date, ', Performance end: ', perf_date);
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = error_message;
    END IF;

    -- 3. Ensure the visitor has a ticket for the event of the performance
    SELECT COUNT(*) > 0 INTO has_ticket
    FROM TICKET t
    JOIN EVENT e ON t.event_id = e.event_id
    JOIN PERFORMANCE p ON e.event_id = p.event_id
    WHERE t.visitor_id = NEW.visitor_id
      AND p.performance_id = NEW.performance_id;

    IF NOT has_ticket THEN
        SET error_message = CONCAT('Visitor must have a ticket to rate a performance. Visitor ID: ', 
                                  NEW.visitor_id, ', Performance ID: ', NEW.performance_id, 
                                  ', Event ID: ', event_id_for_perf);
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = error_message;
    END IF;

    -- 4. Ensure each rating score is between 1 and 5
    IF NEW.artist_interpretation < 1 OR NEW.artist_interpretation > 5 OR
       NEW.sound_lighting < 1 OR NEW.sound_lighting > 5 OR
       NEW.stage_presence < 1 OR NEW.stage_presence > 5 OR
       NEW.organization < 1 OR NEW.organization > 5 OR
       NEW.overall_impression < 1 OR NEW.overall_impression > 5 THEN
        SET error_message = CONCAT('Ratings must be between 1 and 5. Visitor ID: ', 
                                  NEW.visitor_id, ', Performance ID: ', NEW.performance_id);
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = error_message;
    END IF;

    -- 5. Prevent duplicate rating for the same performance by the same visitor
    SELECT COUNT(*) INTO existing_rating
    FROM RATING
    WHERE visitor_id = NEW.visitor_id
      AND performance_id = NEW.performance_id
      AND rating_id <> NEW.rating_id;

    IF existing_rating > 0 THEN
        SET error_message = CONCAT('Visitor has already rated this performance. Visitor ID: ', 
                                  NEW.visitor_id, ', Performance ID: ', NEW.performance_id);
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = error_message;
    END IF;
END;$$


USE `festival`$$
DROP TRIGGER IF EXISTS `trg_resale_validate_buyer_before_insert` $$
USE `festival`$$
CREATE DEFINER = CURRENT_USER TRIGGER `festival`.`trg_resale_validate_buyer_before_insert` BEFORE INSERT ON `RESALE_BUYER_QUEUE` FOR EACH ROW
BEGIN
 -- Έλεγχος αν ο αγοραστής εκδηλώνει ενδιαφέρον είτε για συγκεκριμένη παράσταση και κατηγορία εισιτηρίου,
    -- είτε για συγκεκριμένο εισιτήριο, αλλά όχι και για τα δύο ταυτόχρονα
    DECLARE ticket_available INT;
    IF NOT (
        (NEW.event_id IS NOT NULL AND NEW.ticket_category IS NOT NULL AND NEW.ticket_id IS NULL) OR
        (NEW.event_id IS NULL AND NEW.ticket_category IS NULL AND NEW.ticket_id IS NOT NULL)
    ) THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Ο αγοραστής πρέπει να εκδηλώνει ενδιαφέρον είτε για συγκεκριμένη παράσταση και κατηγορία εισιτηρίου, είτε για συγκεκριμένο εισιτήριο, αλλά όχι και για τα δύο ταυτόχρονα.';
    END IF;
    
    -- Αν ο αγοραστής ενδιαφέρεται για συγκεκριμένο εισιτήριο, έλεγχος αν αυτό είναι διαθέσιμο προς πώληση
    IF NEW.ticket_id IS NOT NULL THEN
        SELECT COUNT(*) INTO ticket_available
        FROM RESALE_SELLER_QUEUE
        WHERE ticket_id = NEW.ticket_id
          AND is_processed = FALSE;  
        
        IF ticket_available = 0 THEN
            SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Το συγκεκριμένο εισιτήριο δεν είναι διαθέσιμο προς πώληση.';
        END IF;
    END IF;
END$$



USE `festival`$$
DROP TRIGGER IF EXISTS `trg_resale_validate_seller_before_insert` $$
USE `festival`$$
CREATE DEFINER = CURRENT_USER TRIGGER `festival`.`trg_resale_validate_seller_before_insert` BEFORE INSERT ON `RESALE_SELLER_QUEUE` FOR EACH ROW
BEGIN
DECLARE ticket_owner INT;
    DECLARE v_is_activated BOOLEAN;
    DECLARE already_listed BOOLEAN;

    -- 1. Έλεγχος ότι ο πωλητής είναι ο ιδιοκτήτης του εισιτηρίου
    SELECT visitor_id, is_activated
    INTO ticket_owner, v_is_activated
    FROM TICKET
    WHERE ticket_id = NEW.ticket_id;

    IF ticket_owner != NEW.visitor_id THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Μόνο ο ιδιοκτήτης του εισιτηρίου μπορεί να το μεταπωλήσει';
    END IF;

    -- 2. Έλεγχος ότι το εισιτήριο δεν έχει ενεργοποιηθεί
    IF v_is_activated = 1 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Τα ενεργοποιημένα εισιτήρια δεν μπορούν να μεταπωληθούν';
    END IF;

    -- 3. Έλεγχος ότι το εισιτήριο δεν είναι ήδη καταχωρημένο προς πώληση
    SELECT COUNT(*) > 0 INTO already_listed
    FROM RESALE_SELLER_QUEUE
    WHERE ticket_id = NEW.ticket_id;

    IF already_listed THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Το εισιτήριο είναι ήδη καταχωρημένο προς πώληση';
    END IF;
END$$



USE `festival`$$
DROP TRIGGER IF EXISTS `trg_event_staff_requirements_before_insert` $$
USE `festival`$$
CREATE DEFINER = CURRENT_USER TRIGGER `festival`.`trg_event_staff_requirements_before_insert`
BEFORE INSERT ON `EVENT_STAFF`
FOR EACH ROW
BEGIN
    DECLARE v_staff_type VARCHAR(45);
    DECLARE venue_capacity INT;
    DECLARE required_security_staff INT;
    DECLARE required_auxiliary_staff INT;
    DECLARE current_security_staff INT;
    DECLARE current_auxiliary_staff INT;

    -- 1. Get staff type for the new assignment
    SELECT staff_type INTO v_staff_type
    FROM STAFF
    WHERE staff_id = NEW.staff_id;

    -- Validate that the staff type is one of the allowed types.
    IF v_staff_type NOT IN ('security', 'auxiliary', 'technical') THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Invalid staff type for event assignment';
    END IF;

    -- 2. Get venue capacity for the event
    SELECT v.max_capacity INTO venue_capacity
    FROM EVENT e
    JOIN VENUE v ON e.venue_id = v.venue_id
    WHERE e.event_id = NEW.event_id;

    -- 3. Calculate required minimum staff for security and auxiliary
    SET required_security_staff = CEILING(venue_capacity * 0.05);
    SET required_auxiliary_staff = CEILING(venue_capacity * 0.02);

    -- 4. Count current assigned staff of each type for the event
    SELECT COUNT(*) INTO current_security_staff
    FROM EVENT_STAFF es
    JOIN STAFF s ON es.staff_id = s.staff_id
    WHERE es.event_id = NEW.event_id
      AND s.staff_type = 'security';

    SELECT COUNT(*) INTO current_auxiliary_staff
    FROM EVENT_STAFF es
    JOIN STAFF s ON es.staff_id = s.staff_id
    WHERE es.event_id = NEW.event_id
      AND s.staff_type = 'auxiliary';

    -- 5. Increment the count for the type being inserted.
    IF v_staff_type = 'security' THEN
        SET current_security_staff = current_security_staff + 1;
    ELSEIF v_staff_type = 'auxiliary' THEN
        SET current_auxiliary_staff = current_auxiliary_staff + 1;
    END IF;
END;$$


USE `festival`$$
DROP TRIGGER IF EXISTS `trg_event_staff_requirements_before_delete` $$
USE `festival`$$
CREATE DEFINER = CURRENT_USER TRIGGER `festival`.`trg_event_staff_requirements_before_delete`
BEFORE DELETE ON `EVENT_STAFF`
FOR EACH ROW
BEGIN
    DECLARE staff_type VARCHAR(45);
    DECLARE venue_capacity INT;
    DECLARE required_security_staff INT;
    DECLARE required_auxiliary_staff INT;
    DECLARE remaining_security_staff INT;
    DECLARE remaining_auxiliary_staff INT;

    -- 1. Get the type of staff being removed
    SELECT s.staff_type INTO staff_type
    FROM STAFF s
    WHERE s.staff_id = OLD.staff_id;

    -- 2. Get venue capacity for the event
    SELECT v.max_capacity INTO venue_capacity
    FROM EVENT e
    JOIN VENUE v ON e.venue_id = v.venue_id
    WHERE e.event_id = OLD.event_id;

    -- 3. Calculate required minimum staff
    SET required_security_staff = CEILING(venue_capacity * 0.05);
    SET required_auxiliary_staff = CEILING(venue_capacity * 0.02);

    -- 4. Count remaining staff of each type (excluding the one being removed)
    SELECT COUNT(*) INTO remaining_security_staff
    FROM EVENT_STAFF es
    JOIN STAFF s ON es.staff_id = s.staff_id
    WHERE es.event_id = OLD.event_id
      AND s.staff_type = 'security'
      AND es.staff_id != OLD.staff_id;

    SELECT COUNT(*) INTO remaining_auxiliary_staff
    FROM EVENT_STAFF es
    JOIN STAFF s ON es.staff_id = s.staff_id
    WHERE es.event_id = OLD.event_id
      AND s.staff_type = 'auxiliary'
      AND es.staff_id != OLD.staff_id;

    -- 5. Prevent deletion if it violates staffing requirements
    IF staff_type = 'security' AND remaining_security_staff < required_security_staff THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Cannot remove security staff. Minimum 5% of venue capacity is required';
    END IF;

    IF staff_type = 'auxiliary' AND remaining_auxiliary_staff < required_auxiliary_staff THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Cannot remove auxiliary staff. Minimum 2% of venue capacity is required';
    END IF;
END$$


USE `festival`$$
DROP TRIGGER IF EXISTS `trg_artist_band_validate_before_insert` $$
USE `festival`$$
CREATE DEFINER = CURRENT_USER TRIGGER `festival`.`trg_artist_band_validate_before_insert`
BEFORE INSERT ON `ARTIST_BAND`
FOR EACH ROW
BEGIN
    DECLARE is_member BOOLEAN;

    -- 1. Check that leave_date (if provided) is after join_date
    IF NEW.leave_date IS NOT NULL AND NEW.leave_date <= NEW.join_date THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Leave date must be after join date';
    END IF;

    -- 2. Check that the artist is not already a current member of the band
    SELECT COUNT(*) > 0 INTO is_member
    FROM ARTIST_BAND
    WHERE artist_id = NEW.artist_id
      AND band_id = NEW.band_id
      AND (leave_date IS NULL OR leave_date > CURRENT_DATE());

    IF is_member THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Artist is already a member of this band';
    END IF;
END$$


DELIMITER ;










-- 2. Δημιουργία του πίνακα RESALE_MATCHES για την καταγραφή των πιθανών αντιστοιχίσεων
CREATE TABLE IF NOT EXISTS RESALE_MATCHES (
  match_id INT NOT NULL AUTO_INCREMENT,
  buyer_queue_id INT,
  seller_queue_id INT,
  ticket_id INT NULL,
  match_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  is_processed BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (match_id)
);

-- 3. Δημιουργία του πίνακα COMPLETED_RESALE_TRANSACTIONS
CREATE TABLE IF NOT EXISTS COMPLETED_RESALE_TRANSACTIONS (
  transaction_id INT NOT NULL AUTO_INCREMENT,
  buyer_queue_id INT NOT NULL,
  seller_queue_id INT NOT NULL,
  ticket_id INT NOT NULL,
  transaction_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  buyer_id INT NOT NULL,
  seller_id INT NOT NULL,
  PRIMARY KEY (transaction_id)
)
ENGINE = InnoDB;

CREATE INDEX idx_resale_transaction_date ON COMPLETED_RESALE_TRANSACTIONS (transaction_date ASC) VISIBLE;

-- 4. Δημιουργία απλοποιημένων triggers που απλώς καταγράφουν τις πιθανές αντιστοιχίσεις
DELIMITER //

-- Trigger για την καταγραφή πιθανών αντιστοιχίσεων όταν προστίθεται ένας πωλητής
CREATE TRIGGER trg_resale_seller_match
AFTER INSERT ON RESALE_SELLER_QUEUE
FOR EACH ROW
BEGIN
    -- Καταγραφή της πιθανής αντιστοίχισης
    INSERT INTO RESALE_MATCHES (seller_queue_id, ticket_id)
    VALUES (NEW.queue_id, NEW.ticket_id);
END //

-- 1. Διόρθωση του trigger για τους αγοραστές
DELIMITER //

DROP TRIGGER IF EXISTS trg_resale_buyer_match //

CREATE TRIGGER trg_resale_buyer_match
AFTER INSERT ON RESALE_BUYER_QUEUE
FOR EACH ROW
BEGIN
    -- Καταγραφή της πιθανής αντιστοίχισης
    INSERT INTO RESALE_MATCHES (buyer_queue_id, ticket_id)
    VALUES (NEW.queue_id, NEW.ticket_id);
END //

DELIMITER ;




-- Διαγραφή της υπάρχουσας stored procedure
DROP PROCEDURE IF EXISTS process_resale_matches;

-- Δημιουργία stored procedure
DELIMITER //

CREATE PROCEDURE process_resale_matches()
BEGIN


-- Βήμα 1: Δημιουργία προσωρινού πίνακα για τους διαθέσιμους πωλητές
CREATE TEMPORARY TABLE IF NOT EXISTS available_sellers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    queue_id INT,
    visitor_id INT,
    ticket_id INT,
    category VARCHAR(45),
    event_id INT,
    listing_date TIMESTAMP,
    rank_in_category INT
);

-- Εισαγωγή των διαθέσιμων πωλητών με rank για FIFO
-- Μόνο όσοι δεν έχουν ήδη επεξεργαστεί (is_processed = FALSE)
INSERT INTO available_sellers (queue_id, visitor_id, ticket_id, category, event_id, listing_date, rank_in_category)
SELECT 
    rsq.queue_id,
    rsq.visitor_id,
    rsq.ticket_id,
    t.category,
    t.event_id,
    rsq.listing_date,
    RANK() OVER (
        PARTITION BY t.category, t.event_id
        ORDER BY rsq.listing_date ASC
    ) AS rank_in_category
FROM RESALE_SELLER_QUEUE rsq
JOIN TICKET t ON rsq.ticket_id = t.ticket_id
WHERE rsq.is_processed = FALSE
ORDER BY rsq.listing_date ASC;

-- Βήμα 2: Δημιουργία προσωρινού πίνακα για τους αγοραστές συγκεκριμένων εισιτηρίων
CREATE TEMPORARY TABLE IF NOT EXISTS specific_ticket_buyers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    queue_id INT,
    visitor_id INT,
    ticket_id INT,
    interest_date TIMESTAMP
);

-- Εισαγωγή των αγοραστών συγκεκριμένων εισιτηρίων
-- Μόνο όσοι δεν έχουν ήδη επεξεργαστεί (is_processed = FALSE)
INSERT INTO specific_ticket_buyers (queue_id, visitor_id, ticket_id, interest_date)
SELECT 
    queue_id,
    visitor_id,
    ticket_id,
    interest_date
FROM RESALE_BUYER_QUEUE
WHERE ticket_id IS NOT NULL
AND is_processed = FALSE
ORDER BY interest_date ASC;

-- Βήμα 3: Δημιουργία προσωρινού πίνακα για τους αγοραστές κατηγορίας/παράστασης
CREATE TEMPORARY TABLE IF NOT EXISTS category_event_buyers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    queue_id INT,
    visitor_id INT,
    category VARCHAR(45),
    event_id INT,
    interest_date TIMESTAMP,
    rank_in_category INT
);

-- Εισαγωγή των αγοραστών κατηγορίας/παράστασης με rank
-- Μόνο όσοι δεν έχουν ήδη επεξεργαστεί (is_processed = FALSE)
INSERT INTO category_event_buyers (queue_id, visitor_id, category, event_id, interest_date, rank_in_category)
SELECT 
    queue_id,
    visitor_id,
    ticket_category,
    event_id,
    interest_date,
    RANK() OVER (
        PARTITION BY ticket_category, event_id
        ORDER BY interest_date ASC
    ) AS rank_in_category
FROM RESALE_BUYER_QUEUE
WHERE ticket_id IS NULL
AND is_processed = FALSE
ORDER BY interest_date ASC;

-- Βήμα 4: Δημιουργία προσωρινού πίνακα για τις τελικές συναλλαγές
CREATE TEMPORARY TABLE IF NOT EXISTS final_transactions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    buyer_queue_id INT,
    seller_queue_id INT,
    ticket_id INT,
    buyer_id INT,
    seller_id INT,
    transaction_type VARCHAR(20)
);

-- Βήμα 5: Εισαγωγή των συναλλαγών για συγκεκριμένα εισιτήρια
INSERT INTO final_transactions (
    buyer_queue_id,
    seller_queue_id,
    ticket_id,
    buyer_id,
    seller_id,
    transaction_type
)
SELECT 
    stb.queue_id,
    s.queue_id,
    stb.ticket_id,
    stb.visitor_id,
    s.visitor_id,
    'specific'
FROM specific_ticket_buyers stb
JOIN available_sellers s ON stb.ticket_id = s.ticket_id
-- Έλεγχος αν ο αγοραστής έχει ήδη εισιτήριο για την παράσταση
WHERE NOT EXISTS (
    SELECT 1 FROM TICKET t
    WHERE t.visitor_id = stb.visitor_id
    AND t.event_id = (SELECT event_id FROM TICKET WHERE ticket_id = stb.ticket_id)
)
AND s.queue_id NOT IN (
    SELECT seller_queue_id FROM final_transactions
)
ORDER BY stb.interest_date ASC, s.listing_date ASC;

-- Ενημέρωση των διαθέσιμων πωλητών
DELETE FROM available_sellers
WHERE queue_id IN (
    SELECT seller_queue_id FROM final_transactions
);

-- Βήμα 6: Εισαγωγή των συναλλαγών για κατηγορία/παράσταση
-- Επιλέγουμε ΜΟΝΟ τους αγοραστές με rank_in_category = 1 και τους πωλητές με rank_in_category = 1
INSERT INTO final_transactions (
    buyer_queue_id,
    seller_queue_id,
    ticket_id,
    buyer_id,
    seller_id,
    transaction_type
)
SELECT 
    ceb.queue_id,
    s.queue_id,
    s.ticket_id,
    ceb.visitor_id,
    s.visitor_id,
    'category'
FROM category_event_buyers ceb
JOIN available_sellers s ON ceb.category = s.category AND ceb.event_id = s.event_id
-- Έλεγχος αν ο αγοραστής έχει ήδη εισιτήριο για την παράσταση
WHERE NOT EXISTS (
    SELECT 1 FROM TICKET t
    WHERE t.visitor_id = ceb.visitor_id
    AND t.event_id = ceb.event_id
)
AND ceb.rank_in_category = 1
AND s.rank_in_category = 1  -- Επιλογή του πρώτου πωλητή για κάθε κατηγορία-παράσταση (FIFO)
AND ceb.queue_id NOT IN (
    SELECT buyer_queue_id FROM final_transactions
)
AND s.queue_id NOT IN (
    SELECT seller_queue_id FROM final_transactions
)
ORDER BY ceb.interest_date ASC, s.listing_date ASC;

-- Αν δεν βρέθηκε αντιστοίχιση με τον πρώτο πωλητή, προχωράμε στους επόμενους
INSERT INTO final_transactions (
    buyer_queue_id,
    seller_queue_id,
    ticket_id,
    buyer_id,
    seller_id,
    transaction_type
)
SELECT 
    ceb.queue_id,
    s.queue_id,
    s.ticket_id,
    ceb.visitor_id,
    s.visitor_id,
    'category_next'
FROM category_event_buyers ceb
JOIN available_sellers s ON ceb.category = s.category AND ceb.event_id = s.event_id
-- Έλεγχος αν ο αγοραστής έχει ήδη εισιτήριο για την παράσταση
WHERE NOT EXISTS (
    SELECT 1 FROM TICKET t
    WHERE t.visitor_id = ceb.visitor_id
    AND t.event_id = ceb.event_id
)
AND ceb.rank_in_category = 1
AND s.rank_in_category > 1  -- Επιλογή των επόμενων πωλητών αν ο πρώτος δεν ταιριάζει
AND ceb.queue_id NOT IN (
    SELECT buyer_queue_id FROM final_transactions
)
AND s.queue_id NOT IN (
    SELECT seller_queue_id FROM final_transactions
)
AND NOT EXISTS (
    -- Έλεγχος αν υπάρχει ήδη αντιστοίχιση για αυτή την κατηγορία-παράσταση
    SELECT 1 FROM final_transactions ft
    JOIN available_sellers s2 ON ft.seller_queue_id = s2.queue_id
    WHERE s2.category = s.category AND s2.event_id = s.event_id
)
ORDER BY ceb.interest_date ASC, s.listing_date ASC;

-- Βήμα 7: Εισαγωγή των νέων συναλλαγών στον πίνακα COMPLETED_RESALE_TRANSACTIONS
-- Προσθέτουμε μόνο τις νέες συναλλαγές, δεν διαγράφουμε τις παλιές
INSERT INTO COMPLETED_RESALE_TRANSACTIONS (
    buyer_queue_id,
    seller_queue_id,
    ticket_id,
    buyer_id,
    seller_id
)
SELECT 
    buyer_queue_id,
    seller_queue_id,
    ticket_id,
    buyer_id,
    seller_id
FROM final_transactions
ORDER BY id ASC;

-- Βήμα 8: Ενημέρωση των εισιτηρίων
UPDATE TICKET t
JOIN final_transactions ft ON t.ticket_id = ft.ticket_id
SET t.visitor_id = ft.buyer_id;

-- Βήμα 9: Σήμανση των εγγραφών ως επεξεργασμένες
UPDATE RESALE_BUYER_QUEUE rbq
JOIN final_transactions ft ON rbq.queue_id = ft.buyer_queue_id
SET rbq.is_processed = TRUE;

UPDATE RESALE_SELLER_QUEUE rsq
JOIN final_transactions ft ON rsq.queue_id = ft.seller_queue_id
SET rsq.is_processed = TRUE;

-- Καθαρισμός των προσωρινών πινάκων
DROP TEMPORARY TABLE IF EXISTS available_sellers;
DROP TEMPORARY TABLE IF EXISTS specific_ticket_buyers;
DROP TEMPORARY TABLE IF EXISTS category_event_buyers;
DROP TEMPORARY TABLE IF EXISTS final_transactions;

-- Εμφάνιση των αποτελεσμάτων
SELECT CONCAT('Η διαδικασία ολοκληρώθηκε με επιτυχία. Βρέθηκαν ', 
             (SELECT COUNT(*) FROM COMPLETED_RESALE_TRANSACTIONS) - 
             (SELECT @prev_count := COUNT(*) FROM COMPLETED_RESALE_TRANSACTIONS WHERE transaction_date < NOW() - INTERVAL 1 SECOND), 
             ' νέες αντιστοιχίσεις.') AS result;

-- Επιστροφή των αποτελεσμάτων μόνο για τις νέες συναλλαγές
SELECT * FROM COMPLETED_RESALE_TRANSACTIONS 
WHERE transaction_date > NOW() - INTERVAL 1 SECOND;

SELECT COUNT(*) AS total_new_transactions FROM COMPLETED_RESALE_TRANSACTIONS 
WHERE transaction_date > NOW() - INTERVAL 1 SECOND;

-- Εμφάνιση των επεξεργασμένων πωλητών και αγοραστών
SELECT * FROM RESALE_SELLER_QUEUE WHERE is_processed = TRUE;
SELECT COUNT(*) AS processed_sellers FROM RESALE_SELLER_QUEUE WHERE is_processed = TRUE;
SELECT * FROM RESALE_BUYER_QUEUE WHERE is_processed = TRUE;
SELECT COUNT(*) AS processed_buyers FROM RESALE_BUYER_QUEUE WHERE is_processed = TRUE;
END //

DELIMITER ;

-- Εκτέλεση της stored procedure
--CALL process_resale_matches();